version: '3.8'

services:
  # Inventory Microservice
  ms-inventory:
    image: ms-inventory
    container_name: linktic-inventory-service
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - linktic-shared-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api-inventory/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  linktic-shared-network:
    external: true 